### PR TITLE
REVERT not authorized merged PR

### PR DESCRIPTION
**Pull request by itsmeurbi**
For merged [PR](https://github.com/Nany-fork/ledger_account/pull/7/files)

### CODE REVIEW

**Comment by itsmeurbi** [comment]
@Nany-fork can you confirm those where the not authorized merged changes?

**Comment by Nany-fork** [comment]
si son esos los cambios

**Comment by Nany-fork** [comment]
de acuerdo

**Comment by itsmeurbi** [comment]
> si son esos los cambios

Merging since approve then

**Pull request closed without merging**
